spring:
    cache:
        type: redis
    data:
        redis:
            host: 192.168.139.128
            port: 6379
            password: 123456
            lettuce:
              pool:
                  max-active: 8
                  max-idle: 8
                  min-idle: 0
                  max-wait: 100
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ''
        url: jdbc:mysql://localhost:3306/Taskmanage?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true


